name: Go

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: yes
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - run: go version
      - name: Install dependancies
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          go install github.com/gzuidhof/tygo@latest
      - name: Build the package
        run: make
      - name: Test the package and, generate coverage reports
        run: go test -v -benchmem -parallel 16 ./... -covermode=atomic -coverprofile=coverage.out
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: yes
          files: ./coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: yes
      - name: Build the frontend
        run: |
          cd ./cahFrontend
          npm i
          npm run build
      - name: Build Storybook
        run: |-
          cd ./cahFrontend
          npm run build-storybook
